version: '2'

services:
  nginx:
    image: liesbaudoin/phpcourse-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/code:cached
    depends_on:
      - php-fpm

  php-fpm:
    image: liesbaudoin/phpcourse-php-fpm
    volumes:
      - ./:/code:cached

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mytodo'
      MYSQL_ROOT_PASSWORD: "s6Y@Q7@!&9PKNX8"
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: "G!dbN0RINeS1ww1P"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/database/:/var/lib/mysql/
